--- 
services: 
  registro: 
    build: 
      context: "."
      dockerfile: Registro/Dockerfile
    ports: 
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - /run/desktop/mnt/host/c/Users/Thomas/.aspnet/https:/root/.aspnet/https/
    #depends_on: 
    #  - bancoDados
    image: ${DOCKER_REGISTRY-}registro
 
  #bancoDados: 
  #    environment:
  #      - SA_PASSWORD = Thomas.19983
  #      - ACCEPT_EULA=Y
  #    image: mcr.microsoft.com/mssql/server
  #    ports: 
  #      - "1450:1433"
  #    volumes: 
  #      - C:\Users\Thomas\Desktop\DADOSSQL:/var/opt/mssql/data
version: "3.4"
