version: "3.4"

services: 
  registro: 
    build: 
      context: .
      dockerfile: Registro/Dockerfile
    ports: 
      - "8080:80"
    depends_on: 
      - bancoDados
    image: ${DOCKER_REGISTRY-}registro
 
  bancoDados: 
      image: mcr.microsoft.com/mssql/server:2019-latest
      environment:
        - SA_PASSWORD=Thomas.19983
        - ACCEPT_EULA=Y
      ports: 
        - "1450:1433"
 

